# golang
export GOROOT="/usr/local/go"
export PATH="$PATH:$GOROOT"
export GOPATH="$HOME/go"
export GOBIN="$GOPATH/bin"
export PATH="$PATH:$GOBIN"
# pnpm
export PNPM_HOME="/home/ykhi/.local/share/pnpm"
export PATH="$PATH:$PNPM_HOME"